[project]
name = "panet-technique-matcher"
version = "0.1.0"
description = "All elements for matching techniques with panet terms"
readme = "README.md"
authors = [
    { name = "JonathanRakotomalala"}
]
requires-python = ">=3.10"
dependencies = [
    "owlready2>=0.48",
    "rapidfuzz>=3.13.0",
]

[project_scripts]
panet_technique_matcher = "panet_technique_matcher:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
name = "testpypi" 
url  = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true