[project]
name = "data_provider"
version = "0.1.0"
description = "gets datas using Openaire"
readme = "README.md"
authors = [
    { name = "JonathanRakotomalala"}
]
requires-python = ">=3.10"
dependencies = []

[project_scripts]
data_provider = "data_provider:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
